### ISSUE TITLE
No permission to publish on `npm`

### ISSUE THREAD

**Issue by weaintplastic** [researchgate/spire#12]
## 🐛 Bug Report

@sbekrin I've just recently fixed a security vulnerable related to `js-yaml` by bumping the version to the latest patch release. I've tried to publish `spire` on `npm` and figured out that I don't have the rights to do so. Would you mind adding me and @justinvdm as contributors on `npm`?

**Comment by sbekrin** [comment]
@weaintplastic sure, please DM me your npm usernames and I'll do it 👍

**Comment by sbekrin** [comment]
I've invited @justinvdm as it seems his GH username matches the one on npmjs.org. Let me know if you need help with anything else!
