### ISSUE TITLE
Commit hook does not find lazy-loaded nodejs

### ISSUE THREAD

**Issue by danez** [researchgate/spire#26]
## 🐛 Bug Report

This happens because the spire bin is a simple js script which uses a hashbang. This unfortunately does not work in certain scenarios. I guess the fix could be to make the actual binary a shellscript which does something along the lines of `exec "script.js" "$@"`. Similar to what other tools like yarn/husky, etc do. I will look into this.

## How to reproduce

Install lazy loaded nodejs, via for example antigen. https://github.com/lukechilds/zsh-nvm#lazy-loading.

This error will pop up:
```
env: node: No such file or directory
```

## Expected behavior

Should correctly run spire.

**Comment by sbekrin** [comment]
Hey @danez, thanks for reporting this one. I'm not an expert in shell scripting & best practices around it. Do you maybe know how other tools are doing it in OS-independent way?

**Comment by danez** [comment]
I cannot reproduce this anymore now.
