### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by danez** [researchgate/spire#3]
## 💬 Question

I would want to create a spire plugin for flow.

The problem I see with flow is that there are a lot of releases, each breaking. So I guess there should be a corresponding spire plugin version for each new released flow version.

So I was wondering if I should create a PR here for that plugin, although I think it might make more sense to do it externally as it seems quite difficult to do in the monorepo?

**Comment by danez** [comment]
Speaking of breaking changes, this might be hard to handle in a monorepo with a single version anyway if I think about. So even if you for example update one eslint plugin, this is technicaly a breaking change and think you probably don't want to create a new major version for that of all packages in the repo.

**Comment by sbekrin** [comment]
That's a good question! I'd suggest making flow a peer dependency for plugin, and then making custom spire preset with specific flow version installed. This way you can safely enforce same flow version per organisation/project via preset rather then plugin.

Like you've mentioned, it might be a bit bumpy while we're figuring out best practises and project structure, but we'll get there. Your feedback is very appreciated :)
