### ISSUE TITLE
Allow gitlab and non-github projects in semantic-release plugin

### ISSUE THREAD

**Issue by danez** [researchgate/spire#43]
## 🚀 Feature Proposal

Currently the github plugin is used in the configuration in `spire-plugin-semantic-release`. We should make it possible to also use the gitlab plugin or non of the two. Currently it is not possible by default to release a non github project (without custom config), because of the github plugin.

**Comment by sbekrin** [comment]
Yeah that's a good point @danez, IIRC semantic-release supports `extends` options which automatically composes all hooks so we probably don't need to. I'll check if we can use default config to make it less opinionated.
