### ISSUE TITLE
Simplify the sharing of prettier config between spire-plugin-eslint, spire-plugin-prettier, IDE and other tools 

### ISSUE THREAD

**Issue by weaintplastic** [researchgate/spire#9]
## 🚀 Feature Proposal

Prettier and its configuration is used by many tools including `spire-plugin-eslint`, `spire-plugin-prettier` and lately by the IDE of your choice (e.g. VSCode). All of them come with a different requirement of where and how the configuration should be stored in order to be picked up successfully. Especially IDE's usually require the configuration to be stored in a file at the root level of your project. To make all tools involved to work together nicely I'd propose to change the way prettier is configured.

Instead of configuring `spire-plugin-prettier` via API, I'd suggest to make it require a config file a the root level of a project. Creating the config can be guided by feedback valuable warnings in the console or/and introducing an additional command for `spire-plugin-prettier` that generates the config file on demand. 

## Motivation

Make the orchestration of prettier configuration between the IDE and plugins that rely on it less painful.

**Comment by sbekrin** [comment]
This is something I've been thinking about for a while. There are tools which require explicit configuration to be set at project root level (like Prettier itself, Renovate Bot, and many others). Spire can't handle it _yet_ as it doesn't control project structure.

We probably can address most of the related issue via codemod feature for project structure (similar idea to [mrm](https://github.com/sapegin/mrm)). Ideally, workflow would be as follows:

1. Creating a new project:
```sh
# creates new project with structure provided by config file
yarn create spire-app --config @researchgate/spire-config
```
2. Updating a project:
```sh
# runs spire's postinstall hooks which does the project codemod
yarn upgrade @researchgate/spire-config
```

I'll do a bit more research on existing tools and will create an issue with a small roadmap/rfc so we can discuss it further. Hope that helps!

**Comment by sbekrin** [comment]
One of the things I found interesting is a _constraints_ feature in Yarn v2 as mentioned in [in this JSConf EU talk](https://youtu.be/XePfzVs852s). It's not clear yet if constraints can be reused or shared between projects, but this is something worth to consider for a specific case you've mentioned @weaintplastic.
